### PR TITLE
Add demo-project

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
recheck

**Comment by morucci** [comment]
recheck

**Comment by TristanCacqueray** [comment]
recheck

**Comment by morucci** [comment]
recheck

**Comment by morucci** [comment]
recheck

**Comment by TristanCacqueray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
recheck

**Review by morucci — APPROVED** [review]

**Pull request merged**
